name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Build IPA
        run: |
          cd Chat.Mobile
          security import AppleDistribution.p12 -P ${{ secrets.P12_PASSWORD }} -A
          open MSChatProd.mobileprovision
          ls
          dotnet workload restore 
          dotnet build -f net6.0-ios -c Release
          cd ..
          cd Chat.Mobile/bin/Release/net6.0-ios/ios-arm64
          ls
