name: Chat.Mobile.Android

on:
  push:
    paths-ignore:
      - 'Chat.Hub/**'
      - 'Chat.Blazor/**'
      - '**/microsoft-chat-hub.yml'
      - '**/microsoft-chat-blazor.yml'
    branches:
      - main
      
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
    
      - name: Build
        run: |
          cd Chat.Mobile
          dotnet workload restore 
          dotnet build -f net6.0-android -c Release
          cd ..
          cd Chat.Mobile/bin/Release/net6.0-android/
          ls
          
      - name: Upload android artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: Chat.Mobile/bin/Release/net6.0-android/


  Test:
    runs-on: windows-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
    
      - name: Test integration
        run: |
          cd Chat.Test.Integration
          dotnet workload restore 
          dotnet test
          
      - name: Download android artifact
        uses: actions/download-artifact@v2
        with:
          name: android-app
          
      - name: Restore nuget (needed for legacy dotnet)
        run: nuget restore 'Chat.sln'
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build uitest
        run: msbuild 'Chat.Test.UI/Chat.Test.UI.csproj' -t:rebuild -verbosity:diag -property:Configuration=Release
  
      - run: npm install -g appcenter-cli
        name: Install app center cli

      - run: appcenter test run uitest --app 'AliFarahnakPFE/Chat.Android' --devices '4724249b' --app-path 'ms.chat.mobile-Signed.apk' --test-series "master" --build-dir 'Chat.Test.UI/Chat.Mobile/bin/Release/net6.0-android' --uitest-tools-dir 'Chat.Test.UI/Chat.Mobile/bin/Release/net6.0-android' --token 'dffe5931ea91c6d6b23c33ea737414d79bbb338b'
        name: Run ui test
