name: Chat.Mobile.Android

on:
  push:
    paths-ignore:
      - 'Chat.Hub/**'
      - 'Chat.Blazor/**'
      - '**/microsoft-chat-hub.yml'
      - '**/microsoft-chat-blazor.yml'
      - 'README.md'
    branches:
      - main
      
jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
    
      - name: Build
        run: |
          cd Chat.Mobile
          dotnet workload restore 
          dotnet build -f net6.0-android -c Debug
          cd ..
          cd Chat.Mobile/bin/Debug/net6.0-android
          ls
          
      - name: Upload Android artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-app
          path: Chat.Mobile/bin/Debug/net6.0-android/


  Test:
    runs-on: windows-latest
    needs: Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
    
      - name: Test integration
        run: |
          cd Chat.Test.Integration
          dotnet workload restore 
          dotnet test
          
      - name: Download Android artifact
        uses: actions/download-artifact@v2
        with:
          name: android-app
          
      - name: Restore MuGet (needed for legacy dotnet)
        run: nuget restore 'Chat.sln'
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build UI Test
        run: msbuild 'Chat.Test.UI/Chat.Test.UI.csproj' -t:rebuild -verbosity:diag -property:Configuration=Debug
  
      - run: npm install -g appcenter-cli
        name: Install App Center CLI

      - run: appcenter test run uitest --app 'AliRezaFarahnak/Chat.Android' --devices '4efb4607' --app-path 'ms.chat.mobile.apk' --test-series "master" --build-dir 'D:\a\Chat\Chat\Chat.Test.UI\bin\Debug\' --uitest-tools-dir 'D:\a\Chat\Chat\Chat.Test.UI\bin\Debug\' --token 'dffe5931ea91c6d6b23c33ea737414d79bbb338b'
        name: Run UI test
        
  DistributeInternal:
    runs-on: windows-latest
    needs: Test
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
   
  GooglePlay:
    runs-on: windows-latest
    needs: DistributeInternal
    steps:
      - name: Code checkout
        uses: actions/checkout@v2
