name: Chat.Mobile.Android

on:
  push:
    paths-ignore:
      - 'Chat.Hub/**'
      - 'Chat.Blazor/**'
      - '**/microsoft-chat-hub.yml'
      - '**/microsoft-chat-blazor.yml'
    branches:
      - main
      
jobs:
  test-integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: test-integration
        run: |
          cd Chat.Test.Integration
          dotnet workload restore 
          dotnet test
  
  build:
    runs-on: windows-latest
    needs: test-integration
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          cd Chat.Mobile
          dotnet workload restore 
          dotnet build -f net6.0-android -c Release
          cd ..
          cd Chat.Mobile/bin/Release/net6.0-android/
          ls
