
name: Chat.Blazor

on:
  push:
    paths-ignore:
      - 'Chat.Mobile/**'
      - 'Chat.Hub/**'
      - 'Chat.Test.**'
      - '**/microsoft-chat-mobile-android.yml'
      - '**/microsoft-chat-hub.yml'
      - 'README.md'
    branches:
      - main
      
jobs:
  build:
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd Chat.Blazor
          dotnet build -c Release
          dotnet publish -c Release -o /myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'microsoft-chat-blazor'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_248169DBE70F4B22AB7EFAE343878F87 }}
          package: .
        
      - name: Delete Local 
        run: rm -r /myapp
