name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          cd Chat.Mobile

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" AppleDistribution.p12
          security set-keychain-settings -lut 21600 AppleDistribution.p12
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" AppleDistribution.p12

          # import certificate to keychain
          security import AppleDistribution.p12 -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k AppleDistribution.p12
          security list-keychain -d user -s AppleDistribution.p12

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp MSChatProd.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles    
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          
      - name: Build IPA
        run: |
          cd Chat.Mobile
          security import AppleDistribution.p12 -P ${{ secrets.P12_PASSWORD }} -A
          open MSChatProd.mobileprovision
          ls
          dotnet workload restore 
          dotnet build -f net6.0-ios -c Release
          cd ..
          cd Chat.Mobile/bin/Release/net6.0-ios/ios-arm64
          ls
