name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Import Code-Signing Certificates
        # You may pin to the exact commit or the version.
        # uses: Apple-Actions/import-codesign-certs@253ddeeac23f2bdad1646faac5c8c2832e800071
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-filepath: 'Chat.Mobile/AppleDistribution.p12'
          p12-password: ${{ secrets.P12_PASSWORD }} 
          
      - name: install-provisioning-profile-github-action
        # You may pin to the exact commit or the version.
        # uses: akiojin/install-provisioning-profile-github-action@e3f58307bd921490aed4691bb568ce4eb2849c62
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          path: 'Chat.Mobile/MSChatProd.mobileprovision'
