name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
      - name: P12 Install
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          p12-filepath: 'Chat.Mobile/AppleDistribution.p12'
          p12-password: ${{ secrets.P12_PASSWORD }} 
          
      - name: Provisioning Profile Install
        uses: akiojin/install-provisioning-profile-github-action@v1.0
        with:
          path: 'Chat.Mobile/MSChatProd.mobileprovision'
    
      - run: cd ~/Library/MobileDevice/Provisioning\ Profiles && ls

