name: Chat.Mobile.iOS
on: push

jobs:
  build_with_signing:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
     
          
      - name: Build IPA
        run: |
          cd Chat.Mobile
          security import AppleDistribution.p12 -P ${{ secrets.P12_PASSWORD }} -A
          open MSChatProd.mobileprovision
