name: Chat.Mobile.iOS

on:
  push:
    branches:
      - main
      
jobs:
  Build:
    runs-on: [self-hosted, macOS, x64]
    steps:
      - run: echo hello
  
  Integration:
    runs-on: windows-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd Chat.Blazor
          dotnet build -f net6.0-ios -c Release -o /iosout
          cd /iosout
          ls
          cd..
          rm -r /iosout
          ls
          
      - run: echo hello
  UI:
    runs-on: windows-latest
    needs: Integration
    steps:
      - run: echo hello
      
  Internal:
    runs-on: windows-latest
    needs: UI
    steps:
      - run: echo hello
        
  AppStore:
    runs-on: windows-latest
    needs: Internal
    steps:
      - run: echo hello
        
